[[established_account]]
vp = "vp_user"
threshold = 1
public_keys = ["tpknam1qza4yla3g7pctjpxu5dkwnqfn4zpuyakw7y6mp4v6wuw0xv8k5eazcf45a8"]

[[validator_account]]
address = "tnam1qxhtj2464egyym7utdkayeuc9lpr5p8f3yxm8hwv"
vp = "vp_user"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "84.46.249.217:26656"

[validator_account.consensus_key]
pk = "tpknam1qq5jhqa2zkccp2wlhkwqqe8tnz80skmnfjmxdz0w40lkw3t86a4m7j38m5q"
authorization = "signam1qzkm2g5t3pdjyxuvhqlp8hj2vnq7a59tvm3mf6mh5768j0u6n9q8y7kdvwzt6zjn7yqwxgrpa2qu59c2x9jw79kvf0luxymg6dac3kcr2ydpx6"

[validator_account.protocol_key]
pk = "tpknam1qqkzw50fz9ftkhdwcmkrhhu2d3l2c4k58d0wpmwpvdlqkcnuw2ydve7m7kw"
authorization = "signam1qpgf4kaz4ccrafd2u77hp94p4t750r9elxr3m2z9x7d8za8tenwcrwdwmrg6qucyzlp46drptwcdttzj2r0wz597sva309qtqjqj87qff50nj6"

[validator_account.tendermint_node_key]
pk = "tpknam1qr8c39tlc2r7ea2ccllwyylamkcyn595cr8kaxl433vd4tsq7475x30gplw"
authorization = "signam1qpcg9ktrmwn9tqmscrvtfcl8v8skar7x6355qzld5audvjx4x4etc5pjnq6nrr0pa7lsuschxd4z8c7vsklwjcx86nudfxyapm0zw0sq3j975s"

[validator_account.eth_hot_key]
pk = "tpknam1qyprzpg8kmnanvh60c7kxkjynr3j3wyrsnu5u2d2ea7mkqc3uhu3edca3hx6c"
authorization = "signam1q9u3yfuwa0s38w4qs9egypy4qn83sqyezhkyz6kqx9l0eht7c42nqv587fdpynusgl0v5es9p7axhm3350eqvxghrqnn30cv225qfh00qqlhuqrr"

[validator_account.eth_cold_key]
pk = "tpknam1qypetsxjrmugstkdcexkh3ep8cshv9l57g375cgkf3533l6wkutdj5cvhfqat"
authorization = "signam1qytxdspqsd4qq2z9hnugtkmchntsy98naluuvxaqkhn6sccpmgaq2k6wyqeqxxa8vca7t3kjmdygcdlcyl4ezxk0xyn6r3pd2sfnpr0cqy3a8q9w"

[validator_account.metadata]
email = "yarnik.bitcoin+namada@gmail.com"

[validator_account.signatures]
tpknam1qza4yla3g7pctjpxu5dkwnqfn4zpuyakw7y6mp4v6wuw0xv8k5eazcf45a8 = "signam1qr0x6539ep9knk9fpgcljxhm2qrv46ry740e9njrpmul6nd7d5tygxrsrwlcg34v6k347d2u4vud6htetxfqe6zsew5c9u7gm0pdq3q0qkkpna"

[[validator_account]]
address = "tnam1qxhtj2464egyym7utdkayeuc9lpr5p8f3yxm8hwv"
vp = "vp_user"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "84.46.249.217:26656"

[validator_account.consensus_key]
pk = "tpknam1qzf9nemc7n5c8tuezpy06sgzu9wuv2geerlulthu2mxtsh3g2e396cqmltt"
authorization = "signam1qq9gddwdpzu9sd9hlh4v2ydqxdavq6chg095crkn7e3hj3pppf8d2csgkwwvkpmsm0xnds4mc50nzxqx9dgekz8drnlsx6rswhl4w2sz785a2s"

[validator_account.protocol_key]
pk = "tpknam1qqdg23v83kkfegmtcvd5z77ayu98rqdtssc0pavhsv4c5ss92uhagspltjn"
authorization = "signam1qqtjdteamtk738nrdkjzchntakvnynyp27cd73225emapz5dexx80hy0atj5l8xkm6pzu9r2wj76t92hdh2ed83eg5ax77tfcq9aurcys0cw3d"

[validator_account.tendermint_node_key]
pk = "tpknam1qzcr0mefgq379l3yqu0gxdu4h050vx5pvxx9q6dk56rgn5jf489eql5c6y0"
authorization = "signam1qrq4ym0ncdlvjnwpxvahtxkjzar73du2g6rvcpensc5v8wacly3jhejgezhqdum2rd65s8uwp5lqcyhx9kdz7e0eac97cvjzdk9gzusq4rmqsk"

[validator_account.eth_hot_key]
pk = "tpknam1qypx9tkefmcn7gxr0y6hdla3wnurfduc9axuaw5y3gtkmw82wz92qeq3mxt8v"
authorization = "signam1qxnj2s8mn7ptwu7xt5zs5msa4ucjmz3xu9ydrd43qsnx6uzvkyqqvglaz7exre4lapnfmlhzkfjka3ng0puure725lxgzstx9ge33d2tqygcckxm"

[validator_account.eth_cold_key]
pk = "tpknam1qypgdx0puh4f0rs9qxd6qgwtmwfajkpvda8r3ynln0k4kv2rv8ejp6sqaml0l"
authorization = "signam1q9tlm4pqzdquzapk0se0juq285llru5dyptft64dxrta74whxfueqh89ee3690p4rqgcgz6uq76ntz0fgg5t4vr7zxptpukz5chfpnfnqyszte77"

[validator_account.metadata]
email = "yarnik.bitcoin+namada@gmail.com"
discord_handle = "wellnode"

[validator_account.signatures]
tpknam1qza4yla3g7pctjpxu5dkwnqfn4zpuyakw7y6mp4v6wuw0xv8k5eazcf45a8 = "signam1qpjfqlmpk6yl7z3urkf43yy6ruuuff3n2mdz4jye6d7zqfyvrad8fv68gzze0p4su56g7af9u9vzavfydfyutflu0g9kq79hd7z295gw6ettm4"

[[bond]]
source = "tnam1qxhtj2464egyym7utdkayeuc9lpr5p8f3yxm8hwv"
validator = "tnam1qxhtj2464egyym7utdkayeuc9lpr5p8f3yxm8hwv"
amount = "1000000"

[bond.signatures]
tpknam1qza4yla3g7pctjpxu5dkwnqfn4zpuyakw7y6mp4v6wuw0xv8k5eazcf45a8 = "signam1qrnmtwufqmh4ugr0m5wjw8xlh6kl6u2s6ca4cfugl78plcxqd80zh5cx6zkue4nhypth0dlk3ag25r4sgl9a3k3zzk9s9dc3sn7juasqzv8d64"
